export default [
  { seed: 1, pick: "Rush", player: "frutibones" },
  { seed: 2, pick: "Queen", player: "HaMadMan" },
  { seed: 3, pick: "Tom Petty", player: "jclaxton2" },
  { seed: 4, pick: "The Who", player: "zkbarbre" },
  { seed: 5, pick: "AC/DC", player: "tres" },
  { seed: 6, pick: "David Bowie", player: "scubajones" },
  { seed: 7, pick: "Van Halen", player: "stevegulls" },
  { seed: 8, pick: "Boston", player: "Mitchell" },
  { seed: 9, pick: "Thin Lizzy", player: "NStreep" },
  { seed: 10, pick: "Blue Oyster Cult", player: "Todd" },
  { seed: 11, pick: "Lynyrd Skynyrd", player: "Todd" },
  { seed: 12, pick: "Fleetwood Mac", player: "NStreep" },
  { seed: 13, pick: "Cheap Trick", player: "Mitchell" },
  { seed: 14, pick: "Motley Crue", player: "stevegulls" },
  { seed: 15, pick: "Meatloaf", player: "scubajones" },
  { seed: 16, pick: "CCR", player: "tres" },
  { seed: 17, pick: "The Beatles", player: "zkbarbre" },
  { seed: 18, pick: "Bruce Springsteen", player: "jclaxton2" },
  { seed: 19, pick: "Prince", player: "HaMadMan" },
  { seed: 20, pick: "ELO", player: "frutibones" },
  { seed: 21, pick: "The Byrds", player: "frutibones" },
  { seed: 22, pick: "The Band", player: "HaMadMan" },
  { seed: 23, pick: "T. Rex", player: "jclaxton2" },
  { seed: 24, pick: "Uriah Heep", player: "zkbarbre" },
  { seed: 25, pick: "Pink Floyd", player: "tres" },
  { seed: 26, pick: "Eagles", player: "scubajones" },
  { seed: 27, pick: "Led Zeppelin", player: "stevegulls" },
  { seed: 28, pick: "Supertramp", player: "Mitchell" },
  { seed: 29, pick: "Judas Priest", player: "NStreep" },
  { seed: 30, pick: "The Police", player: "Todd" },
  { seed: 31, pick: "The Cars", player: "Todd" },
  { seed: 32, pick: "Scorpions", player: "NStreep" },
  { seed: 33, pick: "Big Star", player: "Mitchell" },
  { seed: 34, pick: "Cream", player: "stevegulls" },
  { seed: 35, pick: "Harry Nilsson", player: "scubajones" },
  { seed: 36, pick: "Kansas", player: "tres" },
  { seed: 37, pick: "Roky Erickson", player: "zkbarbre" },
  { seed: 38, pick: "Toto", player: "jclaxton2" },
  { seed: 39, pick: "Chicago", player: "HaMadMan" },
  { seed: 40, pick: "Heart", player: "frutibones" },
];
