export default [
  {
    round: 1,
    matchup: 1,
    winner: "Wu-Tang Clan",
    winningSong:
      "https://open.spotify.com/track/1v5cgIyffYtfEx0swttdoE?si=0daea4974b994fd2",
    loser: "Eminem",
    losingSong: "https://youtu.be/YVkUvmDQ3HY?si=aR_RTQD942Ttw1PA",
    winVotes: 7,
    lossVotes: 2,
    judgeVote: false,
  },
  {
    round: 1,
    matchup: 2,
    winner: "The Notorious BIG",
    winningSong: "https://spotify.link/VOXEwATN8Db",
    loser: "Bone Thugs-N-Harmony",
    losingSong: "https://spotify.link/sIEL8MmL8Db",
    winVotes: 5,
    lossVotes: 4,
    judgeVote: false,
  },
  {
    round: 1,
    matchup: 3,
    winner: "Ice Cube",
    winningSong: "https://spotify.link/2aVWqos69Db",
    loser: "Missy Elliott",
    losingSong: "https://spotify.link/OuHh5cUZ9Db",
    winVotes: 5,
    lossVotes: 4,
    judgeVote: false,
  },
  {
    round: 1,
    matchup: 4,
    winner: "Geto Boys",
    winningSong: "https://spotify.link/k7TbXJDKaEb",
    loser: "Big Tymers",
    losingSong: "https://spotify.link/BFoQuCSIaEb",
    winVotes: 5,
    lossVotes: 4,
    judgeVote: false,
  },
];
