export default [
  { seed: 1, player: "nakatomi", pick: "Wu-Tang Clan" },
  { seed: 2, player: "tres", pick: "Ludacris" },
  { seed: 3, player: "Nstreep", pick: "OutKast" },
  { seed: 4, player: "scubajones", pick: "Megan Thee Stallion" },
  { seed: 5, player: "Todd", pick: "Geto Boys" },
  { seed: 6, player: "WitchHat", pick: "Tyler, the Creator" },
  { seed: 7, player: "HaMadMan", pick: "A Tribe Called Quest" },
  { seed: 8, player: "FrutiBones", pick: "Kendrick Lamar" },
  { seed: 9, player: "FrutiBones", pick: "The Notorious BIG" },
  { seed: 10, player: "HaMadMan", pick: "Madvillain" },
  { seed: 11, player: "WitchHat", pick: "Run the Jewels" },
  { seed: 12, player: "Todd", pick: "Dr. Dre" },
  { seed: 13, player: "scubajones", pick: "Missy Elliott" },
  { seed: 14, player: "Nstreep", pick: "Snoop Dogg" },
  { seed: 15, player: "tres", pick: "Three 6 Mafia" },
  { seed: 16, player: "nakatomi", pick: "MF Doom" },
  { seed: 17, player: "nakatomi", pick: "J Dilla" },
  { seed: 18, player: "tres", pick: "NWA" },
  { seed: 19, player: "Nstreep", pick: "Ice Cube" },
  { seed: 20, player: "scubajones", pick: "Cardi B" },
  { seed: 21, player: "Todd", pick: "Atmosphere" },
  { seed: 22, player: "WitchHat", pick: "Pouya" },
  { seed: 23, player: "HaMadMan", pick: "Bone Thugs-N-Harmony" },
  { seed: 24, player: "FrutiBones", pick: "UGK" },
  { seed: 25, player: "FrutiBones", pick: "Beastie Boys" },
  { seed: 26, player: "HaMadMan", pick: "Frank Ocean" },
  { seed: 27, player: "WitchHat", pick: "Eminem" },
  { seed: 28, player: "Todd", pick: "Jay-Z" },
  { seed: 29, player: "scubajones", pick: "Doja Cat" },
  { seed: 30, player: "Nstreep", pick: "Andre Nickatina" },
  { seed: 31, player: "tres", pick: "Big Tymers" },
  { seed: 32, player: "nakatomi", pick: "Nas" },
];
