export default [
    { seed: 1, player: "HaMadMan", pick: "Black Sabbath" },
    { seed: 2, player: "stevegulls", pick: "Darkest Hour" },
    { seed: 3, player: "Todd", pick: "Iron Maiden" },
    { seed: 4, player: "jclaxton2", pick: "Children of Bodom" },
    { seed: 5, player: "NStreep", pick: "In Flames" },
    { seed: 6, player: "ecryptus", pick: "Morbid Angel" },
    { seed: 7, player: "zkbarbre", pick: "The Black Dahlia Murder" },
    { seed: 8, player: "tres", pick: "Cradle of Filth" },
    { seed: 9, player: "jclaxton2", pick: "Behemoth" },
    { seed: 10, player: "Todd", pick: "Necrophobic" },
    { seed: 11, player: "zkbarbre", pick: "Dissection" },
    { seed: 12, player: "tres", pick: "Slayer" },
    { seed: 13, player: "HaMadMan", pick: "Melvins" },
    { seed: 14, player: "stevegulls", pick: "Vektor" },
    { seed: 15, player: "ecryptus", pick: "Amorphis" },
    { seed: 16, player: "NStreep", pick: "Dawnbringer" },
    { seed: 17, player: "stevegulls", pick: "At the Gates" },
    { seed: 18, player: "tres", pick: "Dimmu Borgir" },
    { seed: 19, player: "jclaxton2", pick: "Metallica" },
    { seed: 20, player: "zkbarbre", pick: "Slugdge" },
    { seed: 21, player: "Todd", pick: "Emperor" },
    { seed: 22, player: "NStreep", pick: "Taake" },
    { seed: 23, player: "HaMadMan", pick: "Baroness" },
    { seed: 24, player: "ecryptus", pick: "Anathema" },
    { seed: 25, player: "Todd", pick: "Ancst" },
    { seed: 26, player: "jclaxton2", pick: "Amon Amarth" },
    { seed: 27, player: "tres", pick: "Gorgoroth" },
    { seed: 28, player: "ecryptus", pick: "Sepultura" },
    { seed: 29, player: "voidsteve", pick: "Iron Reagan" },
    { seed: 30, player: "HaMadMan", pick: "Big Business" },
    { seed: 31, player: "NStreep", pick: "Havukruunu" },
    { seed: 32, player: "zkbarbre", pick: "Hath" },
]