export default [
  {
    round: 1,
    matchup: 1,
    winner: "Hath",
    winningSong: "https://open.spotify.com/track/2OJZloDNtBrzmbxzPB8OQF?si=baf7c388184640f4",
    loser: "Black Sabbath",
    losingSong: "https://open.spotify.com/track/3ex9yveBIpssnR6sVvhwiR?si=526c2cb4787d487b",
    winVotes: 6,
    lossVotes: 2,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 2,
    winner: "Dawnbringer",
    winningSong: "https://open.spotify.com/track/3joYn42sbFmHOShKNtqvd2?si=c8096f3a730e40ca",
    loser: "At the Gates",
    losingSong: "https://open.spotify.com/track/4Jg1FIbHlwoRi0olOJxtcF?si=Cm8GqMCARB-RaODgEHARrw&utm_source=copy-link",
    winVotes: 7,
    lossVotes: 2,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 3,
    winner: "Behemoth",
    winningSong: "https://open.spotify.com/track/4JynkH6Oa9cJ0zUTzYA2UP?si=gBtO8y35QWWNZajEqN15aA&utm_source=copy-link",
    loser: "Anathema",
    losingSong: "https://open.spotify.com/track/4Deqe7PWcOa9KCRYHEMk2e?si=5PeVunAZTeKwMWKDJ-K9Lw&context=spotify%3Aalbum%3A1ByRLwzKcfrEll0hwCUI2I",
    winVotes: 6,
    lossVotes: 3,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 4,
    winner: "Ancst",
    winningSong: "https://open.spotify.com/track/71ojlFTcjYM6TlEP8X2klW?si=eA9sTNFdSrmkk_lrU04Cpg&utm_source=copy-link",
    loser: "Cradle of Filth",
    losingSong: "https://open.spotify.com/track/7KFY0wzKw6h546qTTcaG93?si=gW43YV05RlqYmsx59i6n4g",
    winVotes: 5,
    lossVotes: 4,
    judgeVote: true
  },
  {
    round: 1,
    matchup: 5,
    winner: "In Flames",
    winningSong: "https://open.spotify.com/track/00HgVIkZrAL8WjAN9Et6WW?si=1jKdRj4ASqq-LreHX75r3g&utm_source=copy-link",
    loser: "Sepultura",
    losingSong: "https://open.spotify.com/track/1erRDf98WX0VllciGPYO1H?si=1d281fa8de354324",
    winVotes: 7,
    lossVotes: 2,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 6,
    winner: "Emperor",
    winningSong: "https://open.spotify.com/track/2956v4MaiU78SkPpeTXxhq?si=vfdPvpxvRo6DTJFZFe5lWw&utm_source=copy-link",
    loser: "Slayer",
    losingSong: "https://open.spotify.com/track/01Mpj13vURSO3cCLprPt5T?si=CmEQoZ0eSMapC6NNN-cJGw",
    winVotes: 5,
    lossVotes: 3,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 7,
    winner: "Melvins",
    winningSong: "https://open.spotify.com/track/5oABn2E9jiDrmhDdiNWbKS?si=excTTWfkQqW5OLIXtf-dog&utm_source=copy-link",
    loser: "Slugdge",
    losingSong: "https://open.spotify.com/track/4iD3Pul1828U9zDIJskq6N?si=PxDcy0GkQfWIuBcfwIEWWg",
    winVotes: 5,
    lossVotes: 4,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 8,
    winner: "Children of Bodom",
    winningSong: "https://open.spotify.com/track/23pLHGVFWELvxIiw0CQMaX?si=FXiWmrqTS5GyzletrcApZw&utm_source=copy-link",
    loser: "Iron Reagan",
    losingSong: "https://open.spotify.com/track/60s740UAdIwuHJXpafVXLH?si=eIW1PU4AQYOHrmyf7vdIcA&utm_source=copy-link",
    winVotes: 8,
    lossVotes: 1,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 9,
    winner: "Iron Maiden",
    winningSong: "https://open.spotify.com/track/6wNF6hphTxhUiAmQG3uzbf?si=PNmO0UfJSg2g1hiKqzzFDg&utm_source=copy-link",
    loser: "Big Business",
    losingSong: "https://open.spotify.com/track/2748v8CnwHyDainyfxuVVA?si=HyUELSZFSqmuI65BbgP4rg&utm_source=copy-link",
    winVotes: 7,
    lossVotes: 2,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 10,
    winner: "Vektor",
    winningSong: "https://open.spotify.com/track/57ksenFZL6ipDlpls2cq0Q?si=dO2RnnyYTkitrzkpKxIYzg&utm_source=copy-link",
    loser: "Metallica",
    losingSong: "https://open.spotify.com/track/7MHkweinOceprzkRWIYTTc?si=NOO5VLVCRyy7KDu_gacvsA&utm_source=copy-link",
    winVotes: 5,
    lossVotes: 3,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 11,
    winner: "Dissection",
    winningSong: "https://open.spotify.com/track/2eBuHnGLI81U8IOQvbsyv4",
    loser: "Taake",
    losingSong: "https://open.spotify.com/track/7nzjXGeN3PB5JkQR0qrRZ7?si=_D6_EdUeTI64WoujAIXrnQ&utm_source=copy-link",
    winVotes: 8,
    lossVotes: 1,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 12,
    winner: "Gorgoroth",
    winningSong: "https://open.spotify.com/track/4TnYQva7vmx3MUilwF8lll?si=XYHyDhaHRr6lE6xLydJx2A",
    loser: "Morbid Angel",
    losingSong: "https://open.spotify.com/track/2iDvE0e6TX1pJNyVLFLY6C?si=OXR89c_kTY-WyqFCqB2_zw",
    winVotes: 6,
    lossVotes: 3,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 13,
    winner: "The Black Dahlia Murder",
    winningSong: "https://open.spotify.com/track/0VEk1PEMmFPb0dwoAK30sk",
    loser: "Amon Amarth",
    losingSong: "https://open.spotify.com/track/7rb8JRuyMqJSBOSoaFMtCY?si=9iePS838SjiUPuEKz2ew9g&utm_source=copy-link",
    winVotes: 6,
    lossVotes: 3,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 14,
    winner: "Necrophobic",
    winningSong: "https://open.spotify.com/track/485HGl8zo02nr2kOnBnyqc?si=yfPvGKGyQGuJX5r7sySkiA&utm_source=copy-link",
    loser: "Baroness",
    losingSong: "https://open.spotify.com/track/4qnmquuGKdUiDLh5paURPb?si=99aDBOxVQzC33UuPCUwArQ&utm_source=copy-link",
    winVotes: 7,
    lossVotes: 2,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 15,
    winner: "Amorphis",
    winningSong: "https://open.spotify.com/track/44gPhpuUmdTsNrCr3RHm6J?si=IMggHgXmTOqUwNFOtA4DQg",
    loser: "Dimmu Borgir",
    losingSong: "https://open.spotify.com/track/5SYTManayo7ME6bWtaSKh9?si=vYzp9DbURQuY7fkvYfzfAQ",
    winVotes: 6,
    lossVotes: 2,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 16,
    winner: "Havukruunu",
    winningSong: "https://open.spotify.com/track/597W6rc5DQjJUMs5D6RdeS?si=rBSvmi5PShemmJ7KxVMCOA&utm_source=copy-link",
    loser: "Darkest Hour",
    losingSong: "https://open.spotify.com/track/6KazWkc2U45YgjtEMkSgxC?si=dLLjTU5YTbeCvecvdh1oAA&utm_source=copy-link",
    winVotes: 6,
    lossVotes: 2,
    judgeVote: false
  },
  {
    round: 2,
    matchup: 1,
    winner: "Hath",
    winningSong: "https://open.spotify.com/track/7cKO1bS9EOyNAp8FEVpylu?si=FDgdGQ-pT3eokOj7Ro9wVw",
    loser: "Dawnbringer",
    losingSong: "https://open.spotify.com/track/5e6i89vIAwuWFekHTIkLsa?si=ai8THsmAQ1afddTKYy0pFQ",
    winVotes: 4,
    lossVotes: 4,
    judgeVote: false
  },
  {
    round: 2,
    matchup: 2,
    winner: "Ancst",
    winningSong: "https://open.spotify.com/track/7dlinZqnX6pxNax4wHe9aL?si=-AemE1CmSdmPSOh2mDxyQA&utm_source=copy-link",
    loser: "Behemoth",
    losingSong: "https://open.spotify.com/track/1Ih4F0xiTxCpVlpgB25iWs?si=1P2YR3xeTuqLgmXwlduE-w&utm_source=copy-link",
    winVotes: 5,
    lossVotes: 4,
    judgeVote: false
  },
  {
    round: 2,
    matchup: 3,
    winner: "In Flames",
    winningSong: "https://open.spotify.com/track/6PLoc1jaez1VzQnZYqVgdW?si=ODcEdpYRSAyPiJf7tGix4Q&utm_source=copy-link",
    loser: "Emperor",
    losingSong: "https://open.spotify.com/track/3Y5xeg9oVzPM3kXvrjAtfn?si=T1pwkXedTdS_-3LgnkbLVQ&utm_source=copy-link",
    winVotes: 6,
    lossVotes: 2,
    judgeVote: false
  },
  {
    round: 2,
    matchup: 4,
    winner: "Children of Bodom",
    winningSong: "https://open.spotify.com/track/2BCAAS7eW0g9ecnOFlVixg?si=Jk-2fLbvQOWbaF_tobpmYw&utm_source=copy-link",
    loser: "Melvins",
    losingSong: "https://open.spotify.com/track/5JSk2ijn31XVo0x0wHyWTc?si=Yse9SeMHQFqNzswfboCsSQ&utm_source=copy-link",
    winVotes: 7,
    lossVotes: 1,
    judgeVote: false
  },
  {
    round: 2,
    matchup: 5,
    winner: "Iron Maiden",
    winningSong: "https://open.spotify.com/track/1Ab3hhOw1TJWDgO10vlxNZ?si=IiGxG1_dTaCgJG2FUMxQuA&utm_source=copy-link",
    loser: "Vektor",
    losingSong: "https://open.spotify.com/track/1BmzrwsyzNpCaufNlk19ck?si=wyEbLioITZu36uNnwmHzBQ&utm_source=copy-link",
    winVotes: 7,
    lossVotes: 1,
    judgeVote: false
  },
  {
    round: 2,
    matchup: 6,
    winner: "Dissection",
    winningSong: "https://open.spotify.com/track/4d8eXiHe6QNJhEYtGOsg7E",
    loser: "Gorgoroth",
    losingSong: "https://open.spotify.com/track/0VZAhuEaRQbBUOpYJU9I0Y?si=mdnmDUvrSLiqjHf1VbAFUQ",
    winVotes: 5,
    lossVotes: 4,
    judgeVote: true
  },
  {
    round: 2,
    matchup: 7,
    winner: "The Black Dahlia Murder",
    winningSong: "https://open.spotify.com/track/3oCTRjyXmT1MMn4nVQMKBm",
    loser: "Necrophobic",
    losingSong: "https://open.spotify.com/track/1iLDcnc7RPeb8PCCr8LCAC?si=wEzo5v2WRte7eqNGB-jqgQ&utm_source=copy-link",
    winVotes: 5,
    lossVotes: 4,
    judgeVote: true
  },
  {
    round: 2,
    matchup: 8,
    winner: "Havukruunu",
    winningSong: "https://open.spotify.com/track/21iN5w6neWqVIe50ZF71YX?si=nyWfbsoiRhCqil_esQmz2A&utm_source=copy-link",
    loser: "Amorphis",
    losingSong: "https://open.spotify.com/track/3iv19AOs3L09kiyWjMP7FK?si=TWQGZPUvR06aLlSTWzW3nA",
    winVotes: 5,
    lossVotes: 3,
    judgeVote: false
  },
  {
    round: 3,
    matchup: 1,
    winner: "Hath",
    winningSong: "https://open.spotify.com/track/0I6gGL6Gf7ZDlKVvGsgGtm?si=7d383028f3914730",
    loser: "Ancst",
    losingSong: "https://open.spotify.com/track/1C5CrcqcfZsb3SxzoFt2wM?si=38cd8f18001e4ead",
    winVotes: 5,
    lossVotes: 3,
    judgeVote: true
  },
  {
    round: 3,
    matchup: 2,
    winner: "Children of Bodom",
    winningSong: "https://open.spotify.com/track/5eSeRwNJgAMF6povFqeRwj?si=f58RM8ngTwqWJlbAfjZgSA&utm_source=copy-link",
    loser: "In Flames",
    losingSong: "https://open.spotify.com/track/0avzMYRJEAqB1zzuXVlpyl?si=66f23f6ff3494065",
    winVotes: 5,
    lossVotes: 3,
    judgeVote: false
  },
  {
    round: 3,
    matchup: 3,
    winner: "Dissection",
    winningSong: "https://open.spotify.com/track/7EA4QgKjNayJ3HGOM4nqlY",
    loser: "Iron Maiden",
    losingSong: "https://open.spotify.com/track/5OLzYihCGQqQlqvfkPEwRh?si=5796861d19394d7b",
    winVotes: 5,
    lossVotes: 3,
    judgeVote: false
  },
  {
    round: 3,
    matchup: 4,
    winner: "The Black Dahlia Murder",
    winningSong: "https://open.spotify.com/track/0ZjsvDcQE6rPg3hqYfZwHp",
    loser: "Havukruunu",
    losingSong: "https://open.spotify.com/track/1r70t4eOFMHriaXaFF9Xxf?si=3KmQ9ZETTb6WBmGp-koWDg&utm_source=copy-link",
    winVotes: 6,
    lossVotes: 2,
    judgeVote: false
  },
  {
    round: 4,
    matchup: 1,
    winner: "Children of Bodom",
    winningSong: "https://open.spotify.com/track/6OSAKQOiGL9GvWgHqAxEZf?si=u1CpzEF3QY23GzO4e90lug&utm_source=copy-link",
    loser: "Hath",
    losingSong: "https://open.spotify.com/track/5a2btXxWsSE6jhDaAEJ0iL",
    winVotes: 7,
    lossVotes: 1,
    judgeVote: false
  },
  {
    round: 4,
    matchup: 2,
    winner: "The Black Dahlia Murder",
    winningSong: "https://open.spotify.com/track/77ZxhaxW6hMrhNDMCM3YOX",
    loser: "Dissection",
    losingSong: "https://open.spotify.com/track/2mZe7q35qMc6XWc1UriQTL",
    winVotes: 6,
    lossVotes: 2,
    judgeVote: false
  },
  {
    round: 5,
    matchup: 1,
    winner: "The Black Dahlia Murder",
    winningSong: "https://open.spotify.com/track/40gZAlqBJbZ9gZFyAo53Cj",
    loser: "Children of Bodom",
    losingSong: "https://open.spotify.com/track/0ZdSjHYb7aJdxC0RHju44G?si=hGLIoin6TiKqtwtAw43I5A&utm_source=copy-link",
    winVotes: 6,
    lossVotes: 1,
    judgeVote: false
  },
  
]