export default [
{seed: 1, player: "NStreep", pick: "Avenue Q"},
{seed: 2, player: "zkbarbre", pick: "Les Miserables"},
{seed: 3, player: "Mitchell", pick: "Encanto"},
{seed: 4, player: "HaMadMan", pick: "Jesus Christ Superstar"},
{seed: 5, player: "Coach", pick: "Blues Brothers"},
{seed: 6, player: 'stevegulls', pick: "Book of Mormon"},
{seed: 7, player: 'scubajones', pick: "The Pick of Destiny"},
{seed: 8, player: "frutibones", pick: "Xanadu"},
{seed: 9, player: "frutibones", pick: "The Phantom of the Opera"},
{seed: 10, player: 'scubajones', pick: "Walk Hard"},
{seed: 11, player: 'stevegulls', pick: "The Nightmare Before Christmas"},
{seed: 12, player: "Coach", pick: "South Park - Bigger, Longer, and Uncut"},
{seed: 13, player: "HaMadMan", pick: "The Rocky Horror Picture Show"},
{seed: 14, player: "Mitchell", pick: "A Goofy Movie"},
{seed: 15, player: "zkbarbre", pick: "Frozen 2"},
{seed: 16, player: "NStreep", pick: "The Lion King"},
{seed: 17, player: "NStreep", pick: "Little Shop of Horrors"},
{seed: 18, player: "zkbarbre", pick: "Spamalot"},
{seed: 19, player: "Mitchell", pick: "Mamma Mia"},
{seed: 20, player: "HaMadMan", pick: "Heathers, The Musical"},
{seed: 21, player: "Coach", pick: "The Muppets"},
{seed: 22, player: 'stevegulls', pick: "Aladdin"},
{seed: 23, player: 'scubajones', pick: "Hercules"},
{seed: 24, player: "frutibones", pick: "Chicago"},
{seed: 25, player: "frutibones", pick: "Chess"},
{seed: 26, player: 'scubajones', pick: "Trolls"},
{seed: 27, player: 'stevegulls', pick: "Oklahoma"},
{seed: 28, player: "Coach", pick: "Shrek"},
{seed: 29, player: "HaMadMan", pick: "Popstar"},
{seed: 30, player: "Mitchell", pick: "The Wiz"},
{seed: 31, player: "zkbarbre", pick: "Matilda"},
{seed: 32, player: "NStreep", pick: "The Wizard of Oz"},
]