export default [
  {
    round: 1,
    matchup: 1,
    winner: "Oklahoma",
    winningSong: "https://youtu.be/VEwVAV3VPw4",
    loser: "Avenue Q",
    losingSong: "https://www.youtube.com/watch?v=U0sHAU0aMq4",
    winVotes: 6,
    lossVotes: 2,
    judgeVote: false,
  },
  {
    round: 1,
    matchup: 2,
    winner: "The Phantom of the Opera",
    winningSong: "https://youtu.be/EGb4hj-EXt0",
    loser: "Hercules",
    losingSong: "https://youtu.be/1aUcYFWg99M",
    winVotes: 5,
    lossVotes: 4,
    judgeVote: true,
  },
  {
    round: 1,
    matchup: 3,
    winner: "The Rocky Horror Picture Show",
    winningSong: "https://youtu.be/bc80tFJpTuo",
    loser: "Mamma Mia",
    losingSong: "https://youtu.be/QRoWiTcO7dk",
    winVotes: 6,
    lossVotes: 2,
    judgeVote: false,
  },
  {
    round: 1,
    matchup: 4,
    winner: "Matilda",
    winningSong: "https://youtu.be/EzPZ9VCCRmU",
    loser: "Blues Brothers",
    losingSong: "https://www.youtube.com/watch?v=qdbrIrFxas0",
    winVotes: 7,
    lossVotes: 1,
    judgeVote: false,
  },
  {
    round: 1,
    matchup: 5,
    winner: "Les Miserables",
    winningSong: "https://www.youtube.com/watch?v=42IQ29b8YIU",
    loser: "Popstar",
    losingSong: "https://youtu.be/CI79h2FSnS4",
    winVotes: 6,
    lossVotes: 2,
    judgeVote: false,
  },
  {
    round: 1,
    matchup: 6,
    winner: "Little Shop of Horrors",
    winningSong: "https://youtube.com/watch?v=9DD7VIKZnGA&feature=share7",
    loser: "Walk Hard",
    losingSong: "https://youtu.be/HOi_kZffAho",
    winVotes: 6,
    lossVotes: 2,
    judgeVote: false,
  },
  {
    round: 1,
    matchup: 7,
    winner: "The Muppets",
    winningSong: "https://www.youtube.com/watch?v=cRTjksM3YAs",
    loser: "A Goofy Movie",
    losingSong: "https://www.youtube.com/watch?v=cRTjksM3YAs",
    winVotes: 6,
    lossVotes: 2,
    judgeVote: false,
  },
  {
    round: 1,
    matchup: 8,
    winner: "Book of Mormon",
    winningSong: "https://www.youtube.com/watch?v=hdZ0KGXteQc",
    loser: "Chess",
    losingSong: "https://www.youtube.com/watch?v=mNdCVTCM4Ws",
    winVotes: 5,
    lossVotes: 3,
    judgeVote: false,
  },
  {
    round: 1,
    matchup: 9,
    winner: "Encanto",
    winningSong: "https://www.youtube.com/watch?v=tQwVKr8rCYw",
    loser: "The Wizard of Oz",
    losingSong: "https://www.youtube.com/watch?v=PSZxmZmBfnU",
    winVotes: 6,
    lossVotes: 2,
    judgeVote: false,
  },
  {
    round: 1,
    matchup: 10,
    winner: "The Nightmare Before Christmas",
    winningSong: "https://www.youtube.com/watch?v=ZVuToMilP0A",
    loser: "Heathers, The Musical",
    losingSong: "https://www.youtube.com/watch?v=ry1yQASy1-Y",
    winVotes: 7,
    lossVotes: 1,
    judgeVote: false,
  },
  {
    round: 1,
    matchup: 11,
    winner: "Chicago",
    winningSong: "https://youtu.be/SBM82Ju2kJU",
    loser: "Frozen 2",
    losingSong: "https://www.youtube.com/watch?v=gIOyB9ZXn8s",
    winVotes: 7,
    lossVotes: 1,
    judgeVote: false,
  },
  {
    round: 1,
    matchup: 12,
    winner: "The Pick of Destiny",
    winningSong: "https://youtu.be/uXEyz1mGMEc",
    loser: "Shrek",
    losingSong: "https://www.youtube.com/watch?v=KRasraWyy48",
    winVotes: 8,
    lossVotes: 0,
    judgeVote: false,
  },
  {
    round: 1,
    matchup: 13,
    winner: "Jesus Christ Superstar",
    winningSong: "https://youtu.be/pqoeM18vCaU",
    loser: "Trolls",
    losingSong: "https://youtu.be/9hPgjW2ou9E",
    winVotes: 6,
    lossVotes: 2,
    judgeVote: false,
  },
  {
    round: 1,
    matchup: 14,
    winner: "Aladdin",
    winningSong: "https://youtu.be/mT_8FAMsmCM",
    loser: "South Park - Bigger, Longer, and Uncut",
    losingSong: "https://m.youtube.com/watch?v=6wJXBUfcIOE",
    winVotes: 5,
    lossVotes: 4,
    judgeVote: false,
  },
  {
    round: 1,
    matchup: 15,
    winner: "The Lion King",
    winningSong: "https://www.youtube.com/watch?v=0bGjlvukgHU",
    loser: "Spamalot",
    losingSong: "https://youtu.be/F-fG8c-CMoU",
    winVotes: 5,
    lossVotes: 3,
    judgeVote: false,
  },
  {
    round: 1,
    matchup: 16,
    winner: "Xanadu",
    winningSong: "https://youtu.be/cLi8fTlDEag",
    loser: "The Wiz",
    losingSong: "https://youtu.be/uNKmKOjGUbw",
    winVotes: 5,
    lossVotes: 3,
    judgeVote: false,
  },
  {
    round: 2,
    matchup: 1,
    winner: "The Phantom of the Opera",
    winningSong: "https://www.youtube.com/watch?v=d3NIK-nsI2g",
    loser: "Oklahoma",
    losingSong: "https://www.youtube.com/watch?v=O5APc0z49wg",
    winVotes: 7,
    lossVotes: 1,
    judgeVote: false,
  },
  {
    round: 2,
    matchup: 2,
    winner: "The Rocky Horror Picture Show",
    winningSong: "https://youtu.be/qE1RVUeQzdc",
    loser: "Matilda",
    losingSong: "https://youtu.be/lUpAAHGA28s",
    winVotes: 5,
    lossVotes: 4,
    judgeVote: true,
  },
  {
    round: 2,
    matchup: 3,
    winner: "Little Shop of Horrors",
    winningSong: "https://www.youtube.com/watch?v=YoWom0CCRKM",
    loser: "Les Miserables",
    losingSong: "https://youtu.be/-p6OH7FoWoQ",
    winVotes: 5,
    lossVotes: 4,
    judgeVote: true,
  },
  {
    round: 2,
    matchup: 4,
    winner: "Book of Mormon",
    winningSong: "https://www.youtube.com/watch?v=OKkLV1zE8M0",
    loser: "The Muppets",
    losingSong: "https://www.youtube.com/watch?v=4p1oHev_gPA",
    winVotes: 6,
    lossVotes: 2,
    judgeVote: false,
  },
  {
    round: 2,
    matchup: 5,
    winner: "Encanto",
    winningSong: "https://youtu.be/bvWRMAU6V-c",
    loser: "The Nightmare Before Christmas",
    losingSong: "https://youtu.be/7ckTdwZqP90",
    winVotes: 6,
    lossVotes: 2,
    judgeVote: false,
  },
  {
    round: 2,
    matchup: 6,
    winner: "The Pick of Destiny",
    winningSong: "https://youtu.be/OToWh3nrWn8",
    loser: "Chicago",
    losingSong: "https://youtu.be/CW8T2fcvd8o",
    winVotes: 5,
    lossVotes: 3,
    judgeVote: false,
  },
  {
    round: 2,
    matchup: 7,
    winner: "Jesus Christ Superstar",
    winningSong: "https://youtu.be/NGcIvK7f77o",
    loser: "Aladdin",
    losingSong: "https://youtu.be/Qx91ff77yzM",
    winVotes: 8,
    lossVotes: 0,
    judgeVote: false,
  },
  {
    round: 2,
    matchup: 8,
    winner: "The Lion King",
    winningSong: "https://www.youtube.com/watch?v=25QyCxVkXwQ",
    loser: "Xanadu",
    losingSong: "https://youtu.be/UGWoonk747I?si=TBxgsp0m4JQi8jnN",
    winVotes: 6,
    lossVotes: 2,
    judgeVote: false,
  },
  {
    round: 3,
    matchup: 1,
    winner: "The Rocky Horror Picture Show",
    winningSong: "https://youtu.be/pRTCbfOUTYU?si=FfnXMmJID5eVjmNh",
    loser: "The Phantom of the Opera",
    losingSong: "https://youtu.be/Phzc_ZNBI68?si=zyRn42l5oWiuDjJS",
    winVotes: 5,
    lossVotes: 3,
    judgeVote: false,
  },
  {
    round: 3,
    matchup: 2,
    winner: "Little Shop of Horrors",
    winningSong: "https://www.youtube.com/watch?v=wVdocX8-j8M",
    loser: "Book of Mormon",
    losingSong: "https://youtu.be/vb1fSIX70AE?si=hB3UTemNTNI2sXLZ",
    winVotes: 6,
    lossVotes: 2,
    judgeVote: false,
  },
  {
    round: 3,
    matchup: 3,
    winner: "Encanto",
    winningSong: "https://youtu.be/Yp5nPGWWMh4?si=lkOxiSR8JdjVjEgF",
    loser: "The Pick of Destiny",
    losingSong: "https://youtu.be/La6RP8r9HRI?si=ryfgVZC9YFZUox1g",
    winVotes: 5,
    lossVotes: 3,
    judgeVote: false,
  },
  {
    round: 3,
    matchup: 4,
    winner: "Jesus Christ Superstar",
    winningSong: "https://youtu.be/aAyMKyoQbIQ?si=LGd0iUO3_jl3733q",
    loser: "The Lion King",
    losingSong: "https://youtu.be/kaOIxll4LCA?feature=shared",
    winVotes: 6,
    lossVotes: 2,
    judgeVote: false,
  },
];
