export default [
  { seed: 1, player: "NStreep", pick: "Green Day" },
  { seed: 2, player: "stevegulls", pick: "AFI" },
  { seed: 3, player: "jclaxton2", pick: "Fugazi" },
  { seed: 4, player: "mikeymorgs", pick: "Operation Ivy" },
  { seed: 5, player: "Mitchell", pick: "The Clash" },
  { seed: 6, player: "tres", pick: "NOFX" },
  { seed: 7, player: "Todd", pick: "Against Me!" },
  { seed: 8, player: "ecryptus", pick: "Minor Threat" },
  { seed: 9, player: "mikeymorgs", pick: "Propagandhi" },
  { seed: 10, player: "jclaxton2", pick: "Superchunk" },
  { seed: 11, player: "Todd", pick: "Jimmy Eat World" },
  { seed: 12, player: "ecryptus", pick: "Refused" },
  { seed: 13, player: "NStreep", pick: "Hot Water Music" },
  { seed: 14, player: "stevegulls", pick: "Debt Neglector" },
  { seed: 15, player: "tres", pick: "Weezer" },
  { seed: 16, player: "Mitchell", pick: "Jeff Rosenstock" },
  { seed: 17, player: "jclaxton2", pick: "Hot Snakes" },
  { seed: 18, player: "ecryptus", pick: "Poison Idea" },
  { seed: 19, player: "mikeymorgs", pick: "The Marked Men" },
  { seed: 20, player: "Todd", pick: "The Lawrence Arms" },
  { seed: 21, player: "stevegulls", pick: "Brutal Youth" },
  { seed: 22, player: "Mitchell", pick: "The Thermals" },
  { seed: 23, player: "NStreep", pick: "Saves The Day" },
  { seed: 24, player: "tres", pick: "Lagwagon" },
  { seed: 25, player: "stevegulls", pick: "Bad Idols" },
  { seed: 26, player: "mikeymorgs", pick: "Dead Kennedys" },
  { seed: 27, player: "ecryptus", pick: "Gang of Four" },
  { seed: 28, player: "tres", pick: "Cursive" },
  { seed: 29, player: "jclaxton2", pick: "Descendants" },
  { seed: 30, player: "NStreep", pick: "The Pixies" },
  { seed: 31, player: "Mitchell", pick: "PUP" },
  { seed: 32, player: "Todd", pick: "The Replacements" },
];
