export default [
  {
    round: 0,
    matchup: 1,
    winner: "Jewel",
    winningSong: "https://open.spotify.com/track/7y7aSSTiQfO0Ace4F7yxzE?si=302oA3-aTn-AgPtMv1V7hA",
    loser: "Kid Rock",
    losingSong: "https://open.spotify.com/track/2MVeIebnEeTxfvINcJsaVy?si=1171c8e800f94ba2",
    winVotes: 6,
    lossVotes: 4,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 1,
    winner: "Metallica",
    winningSong: "https://open.spotify.com/track/4k1IS2uF2dGcU3GzOOZqqb?si=FD1HcIblR4OTvq9vjWrsDw&utm_source=copy-link",
    loser: "Insane Clown Posse",
    losingSong: "https://open.spotify.com/track/3ij7wTT8OOy8MhkT6AS5aS?si=IhNJ3q0zTxeVb8nwk0LUAA",
    winVotes: 9,
    lossVotes: 2,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 2,
    winner: "Rage Against the Machine",
    winningSong: "https://open.spotify.com/track/59WN2psjkt1tyaxjspN8fp?si=3Dw69xoFT263s-KhslEbpA&utm_source=copy-link",
    loser: "The Offspring",
    losingSong: "https://open.spotify.com/track/48WEsrIKIPyQzCW4pcf3sh?si=3WmGjJAYQzurZkw4Iummew&utm_source=copy-link",
    winVotes: 10,
    lossVotes: 1,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 3,
    winner: "The Roots",
    winningSong: "https://open.spotify.com/track/76tWml55YabjLsNPRwUfEF?si=c218ce8a95794a12",
    loser: "Los Lobos",
    losingSong: "https://open.spotify.com/track/2WAHi5ZJwDZqGjnhZgZYmU?si=Mdukt3KbTM2IUCbNQjMXxg",
    winVotes: 8,
    lossVotes: 3,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 4,
    winner: "Fatboy Slim",
    winningSong: "https://open.spotify.com/track/3yGy1JYz3zQKlxSgjgpQqX?si=m98WE5kdTZy8d0E7BiS-3g&utm_source=copy-link",
    loser: "Dave Matthews Band",
    losingSong: "https://open.spotify.com/track/4fXoeBGrVWfNKpdcmL8tw6?si=25fbd85399f846b7",
    winVotes: 7,
    lossVotes: 4,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 5,
    winner: "Everclear",
    winningSong: "https://open.spotify.com/track/0gtQpIxMYqLxtSQn52m0Wx?si=D67ddrkpQaybYDMJeA_lKw&utm_source=copy-link",
    loser: "Counting Crows",
    losingSong: "https://open.spotify.com/track/1tjKIXd7DYNklhVSgBxREi?si=dud4d8j8SVOZb2_EOC8ykQ&utm_source=copy-link",
    winVotes: 7,
    lossVotes: 5,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 6,
    winner: "Korn",
    winningSong: "https://open.spotify.com/track/5PgNUYXmICNOudPFWLIuw3?si=d6muHMBGTOWvEjtnSHJpNw",
    loser: "Rusted Root",
    losingSong: "https://open.spotify.com/track/6XK6Zw6JkFsHXzAcMWNiIr?si=8ee0fcdae1234002",
    winVotes: 7,
    lossVotes: 5,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 7,
    winner: "Collective Soul",
    winningSong: "https://open.spotify.com/track/5c3K5Lwh6vcHi98qNYSNx8?si=8c3c3062db2946e0",
    loser: "Jamiroquai",
    losingSong: "https://open.spotify.com/track/47oS7xB31QQUyPCgHpM3VZ?si=c224400f9cc942b0",
    winVotes: 10,
    lossVotes: 2,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 8,
    winner: "George Clinton",
    winningSong: "https://open.spotify.com/track/2a9wXgPKioc8bX1x3PkdSt?si=PNpUkRlqTN2KquYd6QVAEA&utm_source=copy-link",
    loser: "Guster",
    losingSong: "https://open.spotify.com/track/1IVgVwDSYcoZgmbrI7KOk7?si=7BLdatA_QUaybCp39aae2g&utm_source=copy-link",
    winVotes: 9,
    lossVotes: 3,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 9,
    winner: "Ice Cube",
    winningSong: "https://open.spotify.com/track/2Ih217RCGAmyQR68Nn7Cqo?si=iEhIRcrcR-2pK6aKKXwhKA&utm_source=copy-link",
    loser: "Oleander",
    losingSong: "https://open.spotify.com/track/0hgOGzUYKKQbQcWDoJpM6H?si=20URMbz6QEShbC-l4yGhyw",
    winVotes: 8,
    lossVotes: 3,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 10,
    winner: "Bush",
    winningSong: "https://open.spotify.com/track/7waRjsA2ehXv619f47lYOT?si=9d0f4e33ddf747d2",
    loser: "Willie Nelson",
    losingSong: "https://open.spotify.com/track/1tmCPGkgKKurSN1onKcaJt?si=i-yWK231Rte6TLPFNJDjXw&utm_source=copy-link",
    winVotes: 6,
    lossVotes: 5,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 11,
    winner: "DMX",
    winningSong: "https://open.spotify.com/track/4O9ICXbrUTAVR5kkx6xANJ?si=fmi9-mbjQRSSRrY-zHf9CQ",
    loser: "Sevendust",
    losingSong: "https://open.spotify.com/track/25LbeGnYJuqbkxqc8VyhTs?si=0narOfp0TRy8p1WFz5NO1g",
    winVotes: 10,
    lossVotes: 2,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 12,
    winner: "Elvis Costello",
    winningSong: "https://open.spotify.com/track/3oyc1mIdCBGaU55wX7otqM?si=lSqlgnvsQCODGOV5ZyjaOQ&utm_source=copy-link",
    loser: "Lit",
    losingSong: "https://open.spotify.com/track/2zLZuZFgf4mn3af8wILpHS?si=kNHKc1r5TaqLPI4pPuos9w&utm_source=copy-link",
    winVotes: 11,
    lossVotes: 1,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 13,
    winner: "Megadeth",
    winningSong: "https://open.spotify.com/track/3090goAxG6IlpCifA8m9xB?si=XzeMj6ZwTb2Zrl_6GO1rZg&utm_source=copy-link",
    loser: "Red Hot Chili Peppers",
    losingSong: "https://open.spotify.com/track/6pkzrU2RKoPcQJHT7dwlbP?si=Nw-x7NyBT8WktK9f5ScBLw&utm_source=copy-link",
    winVotes: 7,
    lossVotes: 5,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 14,
    winner: "James Brown",
    winningSong: "https://open.spotify.com/track/5cZqsjVs6MevCnAkasbEOX?si=k6koDx0xQAaPS_dWe2WHiQ",
    loser: "Limp Bizkit",
    losingSong: "https://open.spotify.com/track/5vMTfupz6z7wlNiz0xVb4j?si=3d9487a3f979463e",
    winVotes: 8,
    lossVotes: 4,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 15,
    winner: "Alanis Morissette",
    winningSong: "https://open.spotify.com/track/36sZlJgvmP62qcEuAaV1uM?si=YX_rIAiGS2WVEjYlDTXGcA&utm_source=copy-link",
    loser: "Our Lady Peace",
    losingSong: "https://open.spotify.com/track/1XsmgDo7e4g87IwbFykOcP?si=QBl5w6HqQ3-H6SUPYErRNA&utm_source=copy-link",
    winVotes: 8,
    lossVotes: 4,
    judgeVote: false
  },
  {
    round: 1,
    matchup: 16,
    winner: "The Chemical Brothers",
    winningSong: "https://youtu.be/bGPkTyOCjw0",
    loser: "Jewel",
    losingSong: "https://open.spotify.com/track/0llh1DfyLL1rkW3RVtzhL1?si=2ihb39DSTfyan71GFJ8juA",
    winVotes: 7,
    lossVotes: 4,
    judgeVote: false
  },
  {
    round: 2,
    matchup: 1,
    winner: "Metallica",
    winningSong: "https://open.spotify.com/track/7wz8LNfmGZ3C0PwKW9LdDg?si=VotjE7FhQAS1Emayt5fZag",
    loser: "Rage Against the Machine",
    losingSong: "https://open.spotify.com/track/1MQTmpYOZ6fcMQc56Hdo7T?si=q9U9NmqmRCC273akg5MQfg&utm_source=copy-link&fbclid=IwAR0BIv7uH6zMrD7Yo4eIM7i69HSVaTTHKYUggYOkplqfkK2UjGFxvpuVlsY&nd=1",
    winVotes: 9,
    lossVotes: 3,
    judgeVote: false
  },
  {
    round: 2,
    matchup: 2,
    winner: "The Roots",
    winningSong: "https://open.spotify.com/track/0NSYVDo4ryxNWln7TfEyex?si=46aa89fd680e4a26",
    loser: "Fatboy Slim",
    losingSong: "https://open.spotify.com/track/4vUUCGywCsZy0Dk1QFwxTX?si=I24L4ZcuS6iCH6s1G_uAtQ&utm_source=copy-link",
    winVotes: 10,
    lossVotes: 2,
    judgeVote: false
  },
  {
    round: 2,
    matchup: 3,
    winner: "Everclear",
    winningSong: "https://open.spotify.com/track/57a2a5vsEqnZsjcwMuo6Vo?si=90iOzNxvQ4Witc0U_sifjw&utm_source=copy-link",
    loser: "Korn",
    losingSong: "https://open.spotify.com/track/6W21LNLz9Sw7sUSNWMSHRu?si=A_49JqPOS42TH6OhU8i2tA",
    winVotes: 9,
    lossVotes: 3,
    judgeVote: false
  },
  {
    round: 2,
    matchup: 4,
    winner: "George Clinton",
    winningSong: "https://open.spotify.com/track/2w7R3CQgvl8PIKJlwtT9Mv?si=hNf5EGW7QIa-sPR2v-bCtg&utm_source=copy-link",
    loser: "Jamiroquai",
    losingSong: "https://open.spotify.com/track/6y0Etr2KJr0sdcEp7ajoUK?si=8DtxPt_sRjO7XrJWcqccSQ",
    winVotes: 8,
    lossVotes: 4,
    judgeVote: false
  },
  {
    round: 2,
    matchup: 5,
    winner: "Ice Cube",
    winningSong: "https://open.spotify.com/track/2Ih217RCGAmyQR68Nn7Cqo?si=iEhIRcrcR-2pK6aKKXwhKA&utm_source=copy-link",
    loser: "Bush",
    losingSong: "https://open.spotify.com/track/5eilSVtn5pkequUpyV6w9d?si=cc990de112a047cb",
    winVotes: 6,
    lossVotes: 5,
    judgeVote: false
  },
  {
    round: 2,
    matchup: 6,
    winner: "DMX",
    winningSong: "https://open.spotify.com/track/0LWkaEyQRkF0XAms8Bg1fC?si=Gyfcn64CTvWHU62q_tnoOA",
    loser: "Elvis Costello",
    losingSong: "https://open.spotify.com/track/0qvo5kciIqZJn1t8jdfqDn?si=7DldjoQmTqKHqtOGYO6-TQ&utm_source=copy-link",
    winVotes: 8,
    lossVotes: 4,
    judgeVote: false
  },
  {
    round: 2,
    matchup: 7,
    winner: "Megadeth",
    winningSong: "https://open.spotify.com/track/3090goAxG6IlpCifA8m9xB?si=XzeMj6ZwTb2Zrl_6GO1rZg&utm_source=copy-link",
    loser: "James Brown",
    losingSong: "https://open.spotify.com/track/5XeSAezNDk9tuw3viiCbZ3?si=TJl69UF8QyCrQRQDHV3wCg",
    winVotes: 7,
    lossVotes: 6,
    judgeVote: true
  },
  {
    round: 2,
    matchup: 8,
    winner: "The Chemical Brothers",
    winningSong: "https://open.spotify.com/track/3m1JFLpKLYgMi1jf6Bu16P?si=201d5312d2a34a5a",
    loser: "Alanis Morissette",
    losingSong: "https://open.spotify.com/track/3jS7bB0oXVOwGFZn3aE5NV?si=UmFwIBnIQa6B4Twy_mCCnA&utm_source=copy-link",
    winVotes: 7,
    lossVotes: 6,
    judgeVote: true
  },
  {
    round: 3,
    matchup: 1,
    winner: "Metallica",
    winningSong: "https://open.spotify.com/track/54bm2e3tk8cliUz3VSdCPZ?si=JlNoV2XERXKerC3gKU5HLw",
    loser: "The Roots",
    losingSong: "https://open.spotify.com/track/0NSYVDo4ryxNWln7TfEyex?si=6a3304e562104fc3",
    winVotes: 9,
    lossVotes: 3,
    judgeVote: false
  },
  {
    round: 3,
    matchup: 2,
    winner: "George Clinton",
    winningSong: "https://open.spotify.com/track/2X6qfjDzhKQA7UqhzyJrQP?si=87c6e19ee83b4a15",
    loser: "Everclear",
    losingSong: "https://open.spotify.com/track/6BdD561PmmMhpUYI7Qhaut?si=Zg7XhVXzTbabVwATzA-bHg&utm_source=copy-link",
    winVotes: 8,
    lossVotes: 4,
    judgeVote: false
  },
  {
    round: 3,
    matchup: 3,
    winner: "Ice Cube",
    winningSong: "https://open.spotify.com/track/7I2YlEX9rGAAoNtVvd4wW5?si=iEhIRcrcR-2pK6aKKXwhKA&utm_source=copy-link",
    loser: "DMX",
    losingSong: "https://open.spotify.com/track/1lnqjCZfobpQe6DXURSvzn?si=f7gZp75LRViyhlXY5xqt5A",
    winVotes: 10,
    lossVotes: 2,
    judgeVote: false
  },
  {
    round: 3,
    matchup: 4,
    winner: "The Chemical Brothers",
    winningSong: "https://open.spotify.com/track/2drOnGxH4NvagDjre7GXCd?si=24f30bcde230421c",
    loser: "Megadeth",
    losingSong: "https://open.spotify.com/track/4E5xVW505akJX0wcKj8Mpd?si=AGKrbbpwS12B0zf0SdLhBA&utm_source=copy-link",
    winVotes: 7,
    lossVotes: 5,
    judgeVote: false
  },
  {
    round: 4,
    matchup: 1,
    winner: "Metallica",
    winningSong: "https://open.spotify.com/track/3qXEqKdzI3MSGB1FlGMBz5?si=U6x5EbVSQImJuasgDRVq7Q",
    loser: "George Clinton",
    losingSong: "https://open.spotify.com/track/4XRkQloZFcRrCONN7ZQ49Y?si=fsmRmG0mR-KukyQ-X1PZZw&utm_source=copy-link",
    winVotes: 7,
    lossVotes: 6,
    judgeVote: true
  },
  {
    round: 4,
    matchup: 2,
    winner: "Ice Cube",
    winningSong: "https://open.spotify.com/track/3NGT0Td7H4Is1qrlDQJxma?si=66Rar4ifTMuavZi-QhlGSQ&utm_source=copy-link",
    loser: "The Chemical Brothers",
    losingSong: "https://open.spotify.com/track/2drOnGxH4NvagDjre7GXCd?si=24f30bcde230421c",
    winVotes: 7,
    lossVotes: 4,
    judgeVote: false
  },
  {
    round: 5,
    matchup: 1,
    winner: "Metallica",
    winningSong: "https://open.spotify.com/track/7nmvslxDj3o3Y0O0d79A0G?si=zzlKwOfhSVS41pOUrTkYuw",
    loser: "Ice Cube",
    losingSong: "https://open.spotify.com/track/2qOm7ukLyHUXWyR4ZWLwxA?si=stzUhb8QQsyDW6kpE9FQiA&utm_source=copy-link",
    winVotes: 6,
    lossVotes: 5,
    judgeVote: false
  },
]