export default [
  {seed: 1, player: "ecryptus", pick: "Metallica"},
  {seed: 2, player: "Mitchell", pick: "Chemical Brothers"},
  {seed: 3, player: "nakatomi", pick: "Oleander"},
  {seed: 4, player: "frutibones", pick: "George Clinton"},
  {seed: 5, player: "stevegulls", pick: "Everclear"},
  {seed: 6, player: "jclaxton2", pick: "Elvis Costello"},
  {seed: 7, player: "Todd", pick: "Megadeth"},
  {seed: 8, player: "HaMadMan", pick: "Fatboy Slim"},
  {seed: 9, player: "msntrnr", pick: "The Roots"},
  {seed: 10, player: "scubajones", pick: "James Brown"},
  {seed: 11, player: "mikeymorgs", pick: "DMX"},
  {seed: 12, player: "mikeymorgs", pick: "Korn"},
  {seed: 13, player: "scubajones", pick: "Jamiroquai"},
  {seed: 14, player: "msntrnr", pick: "Bush"},
  {seed: 15, player: "HaMadMan", pick: "Alanis Morisette"},
  {seed: 16, player: "Todd", pick: "The Offspring"},
  {seed: 17, player: "jclaxton2", pick: "Rage Against the Machine"},
  {seed: 18, player: "stevegulls", pick: "Our Lady Peace"},
  {seed: 19, player: "frutibones", pick: "Willie Nelson"},
  {seed: 20, player: "nakatomi", pick: "Collective Soul"},
  {seed: 21, player: "Mitchell", pick: "Rusted Root"},
  {seed: 22, player: "ecryptus", pick: "Sevendust"},
  {seed: 23, player: "ecryptus", pick: "Limp Bizkit"},
  {seed: 24, player: "Mitchell", pick: "Los Lobos"},
  {seed: 25, player: "nakatomi", pick: "Dave Matthews Band"},
  {seed: 26, player: "frutibones", pick: "Red Hot Chili Peppers"},
  {seed: 27, player: "stevegulls", pick: "Lit"},
  {seed: 28, player: "jclaxton2", pick: "Counting Crows"},
  {seed: 29, player: "Todd", pick: "Guster"},
  {seed: 30, player: "HaMadMan", pick: "Ice Cube"},
  {seed: 31, player: "msntrnr", pick: "Kid Rock"},
  {seed: 32, player: "scubajones", pick: "Insane Clown Posse"},
  {seed: 33, player: "mikeymorgs", pick: "Jewel"},
]

